trigger:
  branches:
    include:
      - main
pool: selfhostedpool

stages:
  - stage: Dev
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          environment: 'dev'
          tfFolder: 'environments/dev'

  - stage: QA
    dependsOn: Dev
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          environment: 'qa'
          tfFolder: 'environments/qa'

  - stage: Prod
    dependsOn: QA
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          environment: 'prod'
          tfFolder: 'environments/prod'










